output "scaling_plan_id" {
  description = "Resource ID of the AVD scaling plan."
  value       = local.scaling_plan_id
}

output "scaling_plan_name" {
  description = "Name of the AVD scaling plan, as generated by the naming module."
  value       = local.scaling_plan_name
}

output "personal_schedule_ids" {
  description = "Map of personal schedule key -> resource ID (azapi)."
  value       = { for k, v in azapi_resource.personal_schedule : k => v.id }
}

output "is_personal_plan" {
  description = "True when the plan was created as hostPoolType=Personal via azapi."
  value       = local.is_personal_plan
}
