# Generated from legacy/mult/.../vdi_dcr.bicep — do not hand-edit; regenerate if legacy changes.
locals {
  dcr_perf_60 = [
    "\\\\\\\\LogicalDisk(*)\\\\\\\\Avg. Disk Queue Length",
    "\\\\\\\\LogicalDisk(*)\\\\\\\\Avg. Disk sec/Read",
    "\\\\\\\\LogicalDisk(*)\\\\\\\\Avg. Disk sec/Transfer",
    "\\\\\\\\LogicalDisk(*)\\\\\\\\Avg. Disk sec/Write",
    "\\\\\\\\LogicalDisk(*)\\\\\\\\Current Disk Queue Length",
    "\\\\\\\\LogicalDisk(*)\\\\\\\\Disk Bytes/sec",
    "\\\\\\\\LogicalDisk(*)\\\\\\\\Free Megabytes",
    "\\\\\\\\Memory\\\\\\\\Page Reads/sec",
    "\\\\\\\\Memory\\\\\\\\Pages Input/sec",
    "\\\\\\\\Memory\\\\\\\\Page Faults/sec",
    "\\\\\\\\Memory\\\\\\\\Pages/sec",
    "\\\\\\\\PhysicalDisk(*)\\\\\\\\Avg. Disk Queue Length",
    "\\\\\\\\PhysicalDisk(*)\\\\\\\\Avg. Disk sec/Read",
    "\\\\\\\\PhysicalDisk(*)\\\\\\\\Avg. Disk sec/Transfer",
    "\\\\\\\\PhysicalDisk(*)\\\\\\\\Avg. Disk sec/Write",
    "\\\\\\\\PhysicalDisk(*)\\\\\\\\Current Disk Queue Length",
    "\\\\\\\\Processor Information(_Total)\\\\\\\\% Processor Time",
    "\\\\\\\\Processor(*)\\\\\\\\% Interrupt Time",
    "\\\\\\\\System\\\\\\\\Processor Queue Length",
    "\\\\\\\\FSLogix Azure Storage Provider Performance Metrics\\\\\\\\Writes Before Optimization",
    "\\\\\\\\FSLogix Azure Storage Provider Performance Metrics\\\\\\\\Writes After Optimization",
    "\\\\\\\\FSLogix Azure Storage Provider Performance Metrics\\\\\\\\Cumulative Bytes Read",
    "\\\\\\\\FSLogix Azure Storage Provider Performance Metrics\\\\\\\\Cumulative Bytes Written",
    "\\\\\\\\FSLogix Azure Storage Provider Performance Metrics\\\\\\\\Cumulative Write Transactions",
    "\\\\\\\\FSLogix Azure Storage Provider Performance Metrics\\\\\\\\Cumulative Read Transactions",
    "\\\\\\\\FSLogix Azure Storage Provider Performance Metrics\\\\\\\\Bytes Read Per Second",
    "\\\\\\\\FSLogix Azure Storage Provider Performance Metrics\\\\\\\\Bytes Written Per Second",
    "\\\\\\\\FSLogix Azure Storage Provider Performance Metrics\\\\\\\\Write Transactions Per Second",
    "\\\\\\\\FSLogix Azure Storage Provider Performance Metrics\\\\\\\\Read Transactions Per Second",
    "\\\\\\\\FSLogix SMB Storage Provider Performance Metrics\\\\\\\\Writes Before Optimization",
    "\\\\\\\\FSLogix SMB Storage Provider Performance Metrics\\\\\\\\Writes After Optimization",
    "\\\\\\\\FSLogix Virtualization Driver FileId Cache\\\\\\\\Replaced Entry Count",
    "\\\\\\\\FSLogix Virtualization Driver FileId Cache\\\\\\\\Deleted Entry Count",
    "\\\\\\\\FSLogix Virtualization Driver FileId Cache\\\\\\\\Added Entry Count",
    "\\\\\\\\FSLogix Virtualization Driver FileId Cache\\\\\\\\Maximum Access Interval",
    "\\\\\\\\FSLogix Virtualization Driver FileId Cache\\\\\\\\Entry Access Interval",
    "\\\\\\\\FSLogix Virtualization Driver FileId Cache\\\\\\\\Current Memory Usage",
    "\\\\\\\\FSLogix Virtualization Driver FileId Cache\\\\\\\\Current Entry Count",
    "\\\\\\\\FSLogix CCD Driver Performance Metrics\\\\\\\\Elapsed Time in Usermode Notification",
    "\\\\\\\\FSLogix CCD Driver Performance Metrics\\\\\\\\Count of Usermode Notification",
    "\\\\\\\\FSLogix CCD Driver Performance Metrics\\\\\\\\Elapsed Time in Write Data",
    "\\\\\\\\FSLogix CCD Driver Performance Metrics\\\\\\\\Count of Write Data",
    "\\\\\\\\FSLogix CCD Driver Performance Metrics\\\\\\\\External Bytes Read Cumulative",
    "\\\\\\\\FSLogix CCD Driver Performance Metrics\\\\\\\\External Cumulative Reads",
    "\\\\\\\\FSLogix CCD Driver Performance Metrics\\\\\\\\External Bytes Read Per Second",
    "\\\\\\\\FSLogix CCD Driver Performance Metrics\\\\\\\\External Reads Per Second",
    "\\\\\\\\FSLogix CCD Driver Performance Metrics\\\\\\\\Local Bytes Read Cumulative",
    "\\\\\\\\FSLogix CCD Driver Performance Metrics\\\\\\\\Local Cumulative Reads",
    "\\\\\\\\FSLogix CCD Driver Performance Metrics\\\\\\\\Local Bytes Read Per Second",
    "\\\\\\\\FSLogix CCD Driver Performance Metrics\\\\\\\\Local Reads Per Second",
  ]
  dcr_perf_300 = [
    "\\\\\\\\Memory\\\\\\\\% Committed Bytes In Use",
    "\\\\\\\\Memory\\\\\\\\Available MBytes",
    "\\\\\\\\Memory\\\\\\\\Committed Bytes",
    "\\\\\\\\Memory\\\\\\\\Free System Page Table Entries",
    "\\\\\\\\Paging File(*)\\\\\\\\% Usage",
    "\\\\\\\\RemoteFX Network(*)\\\\\\\\Current TCP RTT",
    "\\\\\\\\RemoteFX Network(*)\\\\\\\\Current UDP Bandwidth",
    "\\\\\\\\RemoteFX Graphics(*)\\\\\\\\Average Encoding Time",
    "\\\\\\\\RemoteFX Graphics(*)\\\\\\\\Frame Quality",
    "\\\\\\\\RemoteFX Graphics(*)\\\\\\\\Frames Skipped/Second - Insufficient Client Resources",
    "\\\\\\\\RemoteFX Graphics(*)\\\\\\\\Frames Skipped/Second - Insufficient Network Resources",
    "\\\\\\\\RemoteFX Graphics(*)\\\\\\\\Frames Skipped/Second - Insufficient Server Resources",
    "\\\\\\\\RemoteFX Graphics(*)\\\\\\\\Graphics Compression ratio",
    "\\\\\\\\RemoteFX Graphics(*)\\\\\\\\Input Frames/Second",
    "\\\\\\\\RemoteFX Graphics(*)\\\\\\\\Output Frames/Second",
    "\\\\\\\\RemoteFX Graphics(*)\\\\\\\\Source Frames/Second",
    "\\\\\\\\Terminal Services\\\\\\\\Active Sessions",
    "\\\\\\\\Terminal Services\\\\\\\\Inactive Sessions",
    "\\\\\\\\Terminal Services\\\\\\\\Total Sessions",
    "\\\\\\\\Terminal Services Session(*)\\\\\\\\% Processor Time",
    "\\\\\\\\Terminal Services Session(*)\\\\\\\\Working Set",
    "\\\\\\\\Terminal Services Session(*)\\\\\\\\Working Set Peak",
    "\\\\\\\\User Input Delay per Session(*)\\\\\\\\Max Input Delay",
    "\\\\\\\\User Input Delay per Process(*)\\\\\\\\Max Input Delay",
    "\\\\\\\\Process(*)\\\\\\\\% Processor Time",
    "\\\\\\\\Process(*)\\\\\\\\Working Set",
    "\\\\\\\\LogicalDisk(*)\\\\\\\\% Free Space",
  ]
  dcr_event_xpaths = [
    "Application!*[System[(Level=1 or Level=2 or Level=3 or Level=4)]]",
    "System!*[System[(Level=1 or Level=2 or Level=3 or Level=4)]]",
    "Security!*[System[(Level=1 or Level=2 or Level=3)]]",
    "Microsoft-Windows-TerminalServices-LocalSessionManager/Operational!*[System[(Level=1  or Level=2 or Level=3 or Level=4 or Level=0)]]",
    "Microsoft-Windows-TerminalServices-RemoteConnectionManager/Admin!*[System[(Level=1  or Level=2 or Level=3 or Level=4 or Level=0)]]",
    "Microsoft-Windows-TerminalServices-RemoteConnectionManager/Operational!*[System[(Level=1  or Level=2 or Level=3 or Level=4 or Level=0)]]",
    "Microsoft-FSLogix-Apps/Operational!*[System[(Level=1  or Level=2 or Level=3 or Level=4 or Level=0)]]",
    "Microsoft-FSLogix-Apps/Admin!*[System[(Level=1  or Level=2 or Level=3 or Level=4 or Level=0)]]",
    "Microsoft-Windows-DeviceManagement-Enterprise-Diagnostics-Provider/Admin!*[System[(Level=1  or Level=2 or Level=3 or Level=4 or Level=0)]]",
    "Microsoft-Windows-AppXDeployment/Operational!*[System[(Level=3 or Level=2 or Level=1)]]",
    "Microsoft-Windows-AppXDeploymentServer/Operational!*[System[(Level=3 or Level=2 or Level=1)]]",
    "Microsoft-Windows-AppxPackaging/Operational!*[System[(Level=2 or Level=1)]]",
    "Microsoft-Windows-AppXDeploymentServer/Restricted!*[System[Level=3 or Level=2 or Level=1]]",
  ]
}

