# ---------------------------------------------------------------------------
# Platform — Virtual WAN
#
# Deploys the Azure Virtual WAN. This is a GLOBAL resource: deployed once (in
# environments/vwan) and shared across all regions. Hub modules attach to
# the vwan_id output: Hub01 secured, Hub02 unsecured. Hub03 spare (hub-spare
# module) is optional — kept in code, commented out in env roots until needed.
#
# The name is generated by the naming module — engineers never pass a raw name.
# ---------------------------------------------------------------------------

module "naming" {
  source = "../../naming"

  resource_type   = "virtual_wan"
  location        = var.location
  subscription_id = var.subscription_id
  environment     = var.environment
  description     = var.description
  unique_id       = var.unique_id
}

resource "azurerm_virtual_wan" "this" {
  name                = module.naming.name
  resource_group_name = var.resource_group_name
  location            = var.location
  type                = var.sku
  tags                = var.tags
}
