# TODO(deploy): expose ids / names needed by sibling modules or env stacks.
#
# output "id" {
#   description = "Resource ID of the primary resource."
#   value       = azurerm_TODO.this.id
# }
#
# output "name" {
#   description = "Name generated by modules/naming."
#   value       = module.demo_module_name.name
# }