output "hub_id" {
  description = "Resource ID of the spare virtual hub. No spoke modules consume this yet — reserved for future attachment."
  value       = azurerm_virtual_hub.this.id
}

output "hub_name" {
  description = "Name of the spare virtual hub, as generated by the naming module."
  value       = azurerm_virtual_hub.this.name
}
